### ISSUE TITLE
Replace hard-coded ncov-tools version with a variable.

### ISSUE THREAD

**Issue by DiDigsDNA** [BCCDC-PHL/ncov-tools-nf#10]
https://github.com/BCCDC-PHL/ncov-tools-nf/blob/6da0c770d79086ce911c8709f881df07b9a59f80/main.nf#L17

Replace hard-coded version of `ncov-tools` with a variable to facilitate managing code when using a new version of ncov-tools.

**Comment by dfornika** [comment]
Fixed in https://github.com/BCCDC-PHL/ncov-tools-nf/commit/423af9e809096448ce8999f8a6651831b9c7f205
